{{<video https://youtu.be/playlist?list=PLQqh36zP38-yQ-M5JMdfTALRpJLYtCret&si=GRrGUtMDJokPcSJE >}}

## 1. 10개의 라커 

`1`. 복도에 10개의 라커가 있다. 복도를 어떤 남자가 10개의 라커 문을 전부 연다. 그리고 나서 짝수 번호의 라커를 전부 닫는다. 그 다음에는 번호가 3의 배수인 라커를 순서대로 찾아다니며 열려 있으면 닫고, 닫혀 있으면 연다. 그 다음에는 번호가 4의 배수인 라커를 순서대로 찾아다니며 열려있으면 닫고, 닫혀있으면 연다. 이러한 방식으로 6회차까지 진행한다. 열린 라커의 문은 몇개가 되겠는가?

`(풀이1)`

In [26]:
doors = rep(TRUE,60)
dim(doors) = c(10,6)
doors

      [,1] [,2] [,3] [,4] [,5] [,6]
 [1,] TRUE TRUE TRUE TRUE TRUE TRUE
 [2,] TRUE TRUE TRUE TRUE TRUE TRUE
 [3,] TRUE TRUE TRUE TRUE TRUE TRUE
 [4,] TRUE TRUE TRUE TRUE TRUE TRUE
 [5,] TRUE TRUE TRUE TRUE TRUE TRUE
 [6,] TRUE TRUE TRUE TRUE TRUE TRUE
 [7,] TRUE TRUE TRUE TRUE TRUE TRUE
 [8,] TRUE TRUE TRUE TRUE TRUE TRUE
 [9,] TRUE TRUE TRUE TRUE TRUE TRUE
[10,] TRUE TRUE TRUE TRUE TRUE TRUE

In [27]:
for(n in 2:6){
    doors[,n] = doors[,n-1]
    doors[,n][seq(n,10,n)] = !doors[,n-1][seq(n,10,n)]
}

In [28]:
doors

      [,1]  [,2]  [,3]  [,4]  [,5]  [,6]
 [1,] TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [2,] TRUE FALSE FALSE FALSE FALSE FALSE
 [3,] TRUE  TRUE FALSE FALSE FALSE FALSE
 [4,] TRUE FALSE FALSE  TRUE  TRUE  TRUE
 [5,] TRUE  TRUE  TRUE  TRUE FALSE FALSE
 [6,] TRUE FALSE  TRUE  TRUE  TRUE FALSE
 [7,] TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [8,] TRUE FALSE FALSE  TRUE  TRUE  TRUE
 [9,] TRUE  TRUE FALSE FALSE FALSE FALSE
[10,] TRUE FALSE FALSE FALSE  TRUE  TRUE

In [29]:
sum(doors[,6])

[1] 5

`(풀이2)`

In [125]:
doors = rep(TRUE,10*6)
doors

 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[46] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

In [126]:
dim(doors) = c(10,6)
doors

      [,1] [,2] [,3] [,4] [,5] [,6]
 [1,] TRUE TRUE TRUE TRUE TRUE TRUE
 [2,] TRUE TRUE TRUE TRUE TRUE TRUE
 [3,] TRUE TRUE TRUE TRUE TRUE TRUE
 [4,] TRUE TRUE TRUE TRUE TRUE TRUE
 [5,] TRUE TRUE TRUE TRUE TRUE TRUE
 [6,] TRUE TRUE TRUE TRUE TRUE TRUE
 [7,] TRUE TRUE TRUE TRUE TRUE TRUE
 [8,] TRUE TRUE TRUE TRUE TRUE TRUE
 [9,] TRUE TRUE TRUE TRUE TRUE TRUE
[10,] TRUE TRUE TRUE TRUE TRUE TRUE

In [133]:
flip <- function(doors, n){
    doors[seq(n,10,n)] = !doors[seq(n,10,n)]
    return(doors)
}

In [143]:
for(n in 2:6){
    doors[,n] = flip(doors[,n-1],n)
}

In [144]:
doors

      [,1]  [,2]  [,3]  [,4]  [,5]  [,6]
 [1,] TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [2,] TRUE FALSE FALSE FALSE FALSE FALSE
 [3,] TRUE  TRUE FALSE FALSE FALSE FALSE
 [4,] TRUE FALSE FALSE  TRUE  TRUE  TRUE
 [5,] TRUE  TRUE  TRUE  TRUE FALSE FALSE
 [6,] TRUE FALSE  TRUE  TRUE  TRUE FALSE
 [7,] TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [8,] TRUE FALSE FALSE  TRUE  TRUE  TRUE
 [9,] TRUE  TRUE FALSE FALSE FALSE FALSE
[10,] TRUE FALSE FALSE FALSE  TRUE  TRUE

In [145]:
sum(doors[,6])

[1] 5

`2`. 6번라커는 3회차에서 열려있는가 닫혀있는가? 

`(풀이)`

In [152]:
doors[6,3]

[1] TRUE

`3`. 8번라커는 6회차가 진행되는 동안 몇번이나 열림상태로 있는가?  

`(풀이)`

In [156]:
doors[8,]

[1]  TRUE FALSE FALSE  TRUE  TRUE  TRUE

In [157]:
sum(doors[8,])

[1] 4

`4`. 열고 닫힘이 가장 빈번한 라커는 몇번인가? 

`(풀이1)`

In [12]:
doors[6,]

[1]  TRUE FALSE  TRUE  TRUE  TRUE FALSE

In [13]:
doors[6,]*1

[1] 1 0 1 1 1 0

In [14]:
diff(doors[6,])

[1] -1  1  0  0 -1

In [15]:
abs(diff(doors[6,]))

[1] 1 1 0 0 1

In [16]:
sum(abs(diff(doors[6,])))

[1] 3

In [17]:
count = rep(0,10)
for(n in 1:10){
    count[n] <- sum(abs(diff(doors[n,])))
}
count

 [1] 0 1 1 2 1 3 0 2 1 2

In [18]:
which.max(count)

[1] 6

`(풀이2)`

In [230]:
library(tidyverse)

In [231]:
count = rep(0,10)
for(n in 1:10){
    count[n] <- doors[n,] %>% diff %>% abs %>% sum 
}
which.max(count)


[1] 6

## 2. `matrix`

### A. 매트릭스를 선언하는 방법 

`-` 방법1: 벡터를 만들고, 그것을 row-vector로 해석한뒤 $\to$ bind 

In [24]:
rbind(c(1,2,3,4),c(2,3,4,5))

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    2    3    4    5

`-` 방법2: 벡터를 만들고, 그것을 col-vector로 해석한뒤 $\to$ bind 

In [237]:
cbind(c(1,2,3,4),c(2,3,4,5))

     [,1] [,2]
[1,]    1    2
[2,]    2    3
[3,]    3    4
[4,]    4    5

***참고: 만들어진 매트릭스의 차원을 살펴보는 방법***

In [245]:
A=rbind(c(1,2,3,4),c(2,3,4,5))
A

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    2    3    4    5

In [246]:
dim(A)

[1] 2 4

In [247]:
A=cbind(c(1,2,3,4),c(2,2,3,4))
A

     [,1] [,2]
[1,]    1    2
[2,]    2    2
[3,]    3    3
[4,]    4    4

In [248]:
dim(A)

[1] 4 2

`-` 방법3: 벡터를 선언하고 dim()을 이용하여 차원을 강제셋팅 

In [249]:
A = 1:8

In [250]:
A

[1] 1 2 3 4 5 6 7 8

In [251]:
dim(A)

NULL

In [252]:
dim(A) <- c(2,4) 

In [253]:
dim(A)

[1] 2 4

In [254]:
A

     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

In [255]:
dim(A) <- c(4,2)

In [256]:
A

     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8

In [38]:
dim(A) <- c(3,3)

Error: Error in dim(A) <- c(3, 3): dims [product 9] do not match the length of object [8]


### B. 매트릭스의 원소를 뽑는 방법 

`-` 아래와 같은 매트릭스가 있다고 하자. 

In [261]:
A=rbind(c(1,2,3,4),c(5,6,7,8),c(9,10,11,12))
A

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12

`-` 1열을 뽑고싶다. 

In [263]:
A[,1] 

[1] 1 5 9

`-` 1열,4열을 뽑고싶다. 

In [265]:
A[,c(1,4)]

     [,1] [,2]
[1,]    1    4
[2,]    5    8
[3,]    9   12

`-` 2행을 뽑고싶다. 

In [266]:
A[2,]

[1] 5 6 7 8

`-` 1행과 2행을 뽑고싶다. 

In [267]:
A[c(1,2),]

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8

In [271]:
A[1:2,]

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8

`-` 2행3열의 원소를 뽑고싶다. 즉 (2,3)의 위치에 있는 원소를 뽑고싶다. 

In [44]:
A[2,3]

[1] 7

`-` 2열을 제외하고 뽑고 싶다. 

In [280]:
A[,-2]

     [,1] [,2] [,3]
[1,]    1    3    4
[2,]    5    7    8
[3,]    9   11   12

### C. 매트릭스를 왜 써야하는가? 

`-` 바둑판구조의 자료형을 표현하기 위해서 = 자료를 바둑판 구조로 저장하기 위해서 

`-` 자료를 바둑판(2d-array), 나아가 큐브형태(3d-array)로 저장하면 어떠한 이점이 있는가? 

`-` 자료를 벡터(1d-array)로 저장하면 어떠한 이점이 있는가? 와 같은 질문 
- 프로그래밍 구조상의 이점 
- 계산상의 이점 

`-` 자료를 벡터로 관리하면 어떠한 이점이 생기듯이 자료를 매트릭스로 관리해도 이점이 생긴다. 

## 3. 파이프연산자 

#### %>% 연산자 ($\star\star\star$)

> note: 진짜 중요한 문법입니다. 너무편해요. 

`-` 아래는 같은코드이다. 

In [282]:
sum(1:10)

[1] 55

In [288]:
1:10 %>% sum()

[1] 55

In [289]:
1:10 %>% sum

[1] 55

`-` 아래와 같이 2개의 입력을 받는 함수를 생각하자. 

In [291]:
myfun = function(x,y){
    x**2+y
}

`-` 아래는 같은코드이다. 

In [298]:
myfun(2,3)

[1] 7

In [299]:
2 %>% myfun(3)

[1] 7

`-` 동일한 논리로 아래도 같은코드이다. 

In [300]:
myfun(3,2) 

[1] 11

In [301]:
3 %>% myfun(2)

[1] 11

`-` 입력이 3개인 함수를 만들자. 

In [302]:
myfun2= function(x,y,z){
    x**2 + y*z
}

`-` 아래는 같은코드이다. 

In [58]:
myfun2(2,1,1)

[1] 5

In [59]:
2 %>% myfun2(1,1)

[1] 5

`-` 왜 이러한 일을 해야하는가? (합성함수 처리에 유리)

In [306]:
x = c(1,100,2,3,4)
x

[1]   1 100   2   3   4

In [307]:
x %>% diff 

[1]  99 -98   1   1

In [311]:
x %>% diff %>% abs %>% sum %>% log %>% sqrt

[1] 2.300718

`-` 개념: `x %>% f %>% h %>% g` 는 아래가 연산되는것 

- $x \overset{f}{\to} f(x) \overset{h}{\to} h(f(x)) \overset{g}{\to} g(h(f(x)))$

## 4. HW

복도에 100개의 라커가 있다. 복도를 어떤 남자가 100개의 라커 문을 전부 연다. 그리고 나서 짝수 번호의 라커를 전부 닫는다. 그 다음에는 번호가 3의 배수인 라커를 순서대로 찾아다니며 열려 있으면 닫고, 닫혀 있으면 연다. 그 다음에는 번호가 4의 배수인 라커를 순서대로 찾아다니며 열려있으면 닫고, 닫혀있으면 연다. 이러한 방식으로 50회차까지 진행한다. 48번 라커는 몇번의 열고 닫힘이 있는가? 