{{<video https://youtu.be/playlist?list=PLQqh36zP38-ykLSHbfcQj5J02t4X-q_JW&si=oXe2a7axdfdLlsxD >}}

## 1. 벡터와 행렬의 결합

`# 예제1` 

In [2]:
x <- c(1,2,3)
y <- c(1,2,3,4)

In [6]:
c(x,y)

[1] 1 2 3 1 2 3 4

In [7]:
c(y,x)

[1] 1 2 3 4 1 2 3

In [8]:
c(-1,x)

[1] -1  1  2  3

In [34]:
c(x,2,2,2,y)

 [1] 1 2 3 2 2 2 1 2 3 4

- c는 사실 `결합하라`라는 의미를 가짐 

`#`

`# 예제2` -- 차원이 맞지 않을 경우 

In [65]:
x<-c(1,2,3,4)
y<-c(1,2)
cbind(x,y)

     x y
[1,] 1 1
[2,] 2 2
[3,] 3 1
[4,] 4 2

In [14]:
x<-c(1,2,3,4)
cbind(1,x)

       x
[1,] 1 1
[2,] 1 2
[3,] 1 3
[4,] 1 4

In [15]:
x<-c(1,2,3,4)
y<-c(1,2)
rbind(x,y)

  [,1] [,2] [,3] [,4]
x    1    2    3    4
y    1    2    1    2

`#`

`# 예제3`

In [16]:
x<-c(1,2,3)
y<-c(4,5)

In [21]:
cbind(1,c(x,y))

     [,1] [,2]
[1,]    1    1
[2,]    1    2
[3,]    1    3
[4,]    1    4
[5,]    1    5

`#`

`# 예제4`

In [22]:
X<-rbind(1:5,6:10)
y<-c(1,2)

In [36]:
cbind(X,y,y,X)

                y y           
[1,] 1 2 3 4  5 1 1 1 2 3 4  5
[2,] 6 7 8 9 10 2 2 6 7 8 9 10

`*` 이름을 지우기 위해서는 아래와 같이 하면 된다.

In [52]:
mat = cbind(X,y,y,X)
colnames(mat)= NULL 
mat

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
[1,]    1    2    3    4    5    1    1    1    2     3     4     5
[2,]    6    7    8    9   10    2    2    6    7     8     9    10

`#`

`# 예제5`

In [53]:
X<-rbind(1:5,6:10)
rbind(X,1)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10
[3,]    1    1    1    1    1

`#`

`# 예제6`

In [56]:
X <- rbind(1:5,6:10,1:5)
Y <- cbind(1:3,4:6,7:9)

In [60]:
cbind(X,Y)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]    1    2    3    4    5    1    4    7
[2,]    6    7    8    9   10    2    5    8
[3,]    1    2    3    4    5    3    6    9

In [64]:
rbind(X,Y)

Error: Error in rbind(X, Y): number of columns of matrices must match (see arg 2)


`#`

## 2. 벡터관련 연산 

`# 예제1`

In [74]:
c(1,2,6) %in% c(1,2,3,4)

[1]  TRUE  TRUE FALSE

`#`

`# 예제2`

In [77]:
union(c(1,1,2,2),c(2,3,4))

[1] 1 2 3 4

`#`

`# 예제3`

In [77]:
intersect(1:5,2:6)

[1] 2 3 4 5

`#`

## 3. 자료의변환 

`# motivating ex` -- 20부터 30까지의 정수중 홀수를 출력하라

In [92]:
x = 20:30
x

 [1] 20 21 22 23 24 25 26 27 28 29 30

In [103]:
x %% 2

 [1] 0 1 0 1 0 1 0 1 0 1 0

In [99]:
as.logical(x %% 2)

 [1] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE

In [100]:
x[as.logical(x %% 2)]

[1] 21 23 25 27 29

`#`

`# 예제1`

In [114]:
x = "123"
x

[1] "123"

In [119]:
as.numeric(x) # as.double(x) 와 동일

[1] 123

In [120]:
as.logical(x)

[1] NA

`#`

`# 예제2`

In [122]:
x = "1.23"

In [125]:
as.numeric(x) # as.double(x) 와 동일

[1] 1.23

In [126]:
as.logical(x)

[1] NA

`#`

`# 예제3`

In [127]:
x = 3.14

In [128]:
as.character(x)

[1] "3.14"

In [129]:
as.logical(x)

[1] TRUE

`#`

`# 예제4`

In [130]:
x = 0

In [131]:
as.character(x)

[1] "0"

In [132]:
as.logical(x)

[1] FALSE

`#`

`# 예제5`

In [133]:
x = -5:5
x

 [1] -5 -4 -3 -2 -1  0  1  2  3  4  5

In [134]:
as.character(x)

 [1] "-5" "-4" "-3" "-2" "-1" "0"  "1"  "2"  "3"  "4"  "5" 

In [135]:
as.logical(x)

 [1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE

`#`

`# 예제6` 

In [141]:
x = -1:1
x

[1] -1  0  1

In [142]:
as.matrix(x)

     [,1]
[1,]   -1
[2,]    0
[3,]    1

`#`

`# 예제7`

In [143]:
x = cbind(-1:1)
x

     [,1]
[1,]   -1
[2,]    0
[3,]    1

In [147]:
as.vector(x)

[1] -1  0  1

`#`

`# 예제8`

In [149]:
x = rbind(-1:1)
x

     [,1] [,2] [,3]
[1,]   -1    0    1

In [150]:
as.vector(x)

[1] -1  0  1

`#`

`# 예제9`

In [151]:
x = cbind(c(1,2),c(3,4))
x

     [,1] [,2]
[1,]    1    3
[2,]    2    4

In [152]:
as.vector(x)

[1] 1 2 3 4

`#`

`# 예제10`

In [156]:
x = c(1,2,4,3)
x

[1] 1 2 4 3

In [157]:
as.logical(as.matrix(x))

[1] TRUE TRUE TRUE TRUE

In [166]:
as.matrix(as.logical(x))

     [,1]
[1,] TRUE
[2,] TRUE
[3,] TRUE
[4,] TRUE

`#`

## 4. 숙제

`1`. 아래와 같은 벡터가 있다고 하자. 

In [1]:
x <- -5:0 
y <- 1:5 

두 벡터를 이용하여 아래와 같은 벡터를 만들라. 

In [172]:
# 출력예시 

 [1] -5 -4 -3 -2 -1  0  1  2  3  4  5

`(풀이)`

In [7]:
c(x,y)

 [1] -5 -4 -3 -2 -1  0  1  2  3  4  5

`2`. 아래와 같은 벡터가 있다고 하자. 

In [8]:
x <- c(1,0,1,1,0)
x

[1] 1 0 1 1 0

1을 TRUE로 0을 FALSE로 바꾸라. 즉 아래의 결과를 얻어라. 

In [176]:
# 출력예시

[1]  TRUE FALSE  TRUE  TRUE FALSE

`(풀이)`

In [10]:
as.logical(x)

[1]  TRUE FALSE  TRUE  TRUE FALSE