In [155]:
# {{<video https://youtu.be/playlist?list=PLQqh36zP38-yQ-M5JMdfTALRpJLYtCret&si=GRrGUtMDJokPcSJE >}}

## 1. 벡터, 행렬의 결합

`# 예제1` 

In [28]:
x<-c(1,2,3)
y<-c(1,2,3,4)

In [29]:
x

[1] 1 2 3

In [30]:
y

[1] 1 2 3 4

In [31]:
c(x,y)

[1] 1 2 3 1 2 3 4

In [32]:
c(y,x)

[1] 1 2 3 4 1 2 3

In [34]:
c(x,2,2,2,y)

 [1] 1 2 3 2 2 2 1 2 3 4

- c는 사실 `결합하라`라는 의미를 가짐 

`#`

`# 예제2` -- 차원이 맞지 않을 경우 

In [37]:
x<-c(1,2,3,4)
y<-c(1,2)
cbind(x,y)

     x y
[1,] 1 1
[2,] 2 2
[3,] 3 1
[4,] 4 2

In [38]:
x<-c(1,2,3,4)
cbind(1,x)

       x
[1,] 1 1
[2,] 1 2
[3,] 1 3
[4,] 1 4

In [39]:
x<-c(1,2,3,4)
y<-c(1,2)
rbind(x,y)

  [,1] [,2] [,3] [,4]
x 1    2    3    4   
y 1    2    1    2   

`#`

`# 예제3`

In [40]:
x<-c(1,2,3)
y<-c(4,5)

In [41]:
cbind(1,c(x,y))

     [,1] [,2]
[1,] 1    1   
[2,] 1    2   
[3,] 1    3   
[4,] 1    4   
[5,] 1    5   

`#`

`# 예제4`

In [42]:
X<-rbind(1:5,6:10)
y<-c(1,2)

In [43]:
X

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  

In [44]:
y

[1] 1 2

In [47]:
cbind(X,y,y,X)

                y y           
[1,] 1 2 3 4  5 1 1 1 2 3 4  5
[2,] 6 7 8 9 10 2 2 6 7 8 9 10

`*` 이름을 지우기 위해서는 아래와 같이 하면 된다.

In [51]:
XyyX= cbind(X,y,y,X)
colnames(XyyX)= NULL 
XyyX

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
[1,] 1    2    3    4     5   1    1    1    2    3     4      5   
[2,] 6    7    8    9    10   2    2    6    7    8     9     10   

`#`

`# 예제5`

In [52]:
X<-rbind(1:5,6:10)
rbind(X,1)

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  
[3,] 1    1    1    1     1  

`#`

`# 예제6`

In [53]:
X <- rbind(1:5,6:10,1:5)
Y <- cbind(1:3,4:6,7:9)

In [54]:
X

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  
[3,] 1    2    3    4     5  

In [55]:
Y

     [,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   

In [56]:
cbind(X,Y)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    2    3    4     5   1    4    7   
[2,] 6    7    8    9    10   2    5    8   
[3,] 1    2    3    4     5   3    6    9   

In [57]:
rbind(X,Y)

ERROR: Error in rbind(X, Y): number of columns of matrices must match (see arg 2)


- 드디어 에러!!

`#`

## 2. 벡터관련 연산 

`# 예제1`

In [76]:
c(1,2,5) %in% c(1,2,3,4)

[1]  TRUE  TRUE FALSE

`#`

`# 예제2`

In [77]:
union(c(1,1,2,2),c(2,3,4))

[1] 1 2 3 4

`#`

`# 예제3`

In [82]:
intersect(1:5,2:6)

[1] 2 3 4 5

`#`

## 3. 자료의변환 

`# motivating ex` -- 20부터 30까지의 정수중 홀수를 출력하라

In [20]:
x = 20:30
x

[1] 20 21 22 23 24 25 26 27 28 29 30

In [22]:
x %% 2

[1] 0 1 0 1 0 1 0 1 0 1 0

In [26]:
x[as.logical(x%%2)] # 이런거 알아두면 편함

[1] 21 23 25 27 29

`#`

`# 예제1`

In [99]:
x = "123"
x

[1] "123"

In [100]:
typeof(x)

[1] "character"

In [101]:
as.numeric(x) # as.double(x) 와 동일

[1] 123

In [102]:
as.logical(x)

[1] NA

`#`

`# 예제2`

In [103]:
x = "1.23"

In [105]:
as.numeric(x) # as.double(x) 와 동일

[1] 1.23

In [106]:
as.logical(x)

[1] NA

`#`

`# 예제3`

In [107]:
x = 3.14

In [89]:
as.character(x)

[1] "3.14"

In [109]:
as.logical(x)

[1] TRUE

`#`

`# 예제4`

In [110]:
x = 0

In [112]:
as.character(x)

[1] "0"

In [114]:
as.logical(x)

[1] FALSE

`#`

`# 예제5`

In [121]:
x = -5:5
x

[1] -5 -4 -3 -2 -1  0  1  2  3  4  5

In [122]:
as.character(x)

[1] "-5" "-4" "-3" "-2" "-1" "0"  "1"  "2"  "3"  "4"  "5"

In [123]:
as.logical(x)

[1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE

`#`

`# 예제6` 

In [134]:
x = -1:1
x

[1] -1  0  1

In [135]:
as.matrix(x)

[,1]
[1,] -1  
[2,]  0  
[3,]  1

`#`

`# 예제7`

In [132]:
x = cbind(-1:1)
x

[,1]
[1,] -1  
[2,]  0  
[3,]  1

In [133]:
as.vector(x)

[1] -1  0  1

`#`

`# 예제8`

In [136]:
x = rbind(-1:1)
x

[,1] [,2] [,3]
[1,] -1   0    1

In [137]:
as.vector(x)

[1] -1  0  1

`#`

`# 예제9`

In [140]:
x = cbind(c(1,2),c(3,4))
x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [141]:
as.vector(x)

[1] 1 2 3 4

`#`

`# 예제10`

In [152]:
x = c(1,2,4,3)
x

[1] 1 2 4 3

In [153]:
as.logical(as.matrix(x))

[1] TRUE TRUE TRUE TRUE

In [154]:
as.matrix(as.logical(x))

[,1]
[1,] TRUE
[2,] TRUE
[3,] TRUE
[4,] TRUE

`#`