{{<video https://youtu.be/playlist?list=PLQqh36zP38-wHEoUFt3MKpaIN0EBv40kJ&si=MWASI-RKTW8uFD2D >}}

## 1. str -- 고급

### A. `fstring`

`-` 예제1

In [210]:
a=1
b=2
print(f'a+b = {a+b}')

a+b = 3


`-` 예제2

In [215]:
a=2
b=3.141592
print(f'a*b = {a*b:.4f}')

a*b = 6.2832


`-` 예제3

In [220]:
a=3.141592
print(f'2a = {2*a:.2f}\t3a = {3*a:.2f}')

2a = 6.28	3a = 9.42


### B. string과 `for`문

`-` 예제1

In [234]:
for s in 'jbnu':
    print(2*s)

jj
bb
nn
uu


`-` 예제2

In [240]:
for s in 'jbnu':
    print(s.upper())

J
B
N
U


### C. `in` 연산자

In [241]:
s = 'jbnu'

In [244]:
'b' in s

True

In [245]:
'c' in s

False

In [246]:
'jb' in s

True

In [248]:
'jn' in s

False

### D. `split`과 `join`

`-` 예제1

In [255]:
'2021.08.14'.split('.')

['2021', '08', '14']

`-` 예제2

In [256]:
'asdf'*2

'asdfasdf'

In [259]:
('asdf'*2).split('f')

['asd', 'asd', '']

`-` 예제3

In [273]:
'-'.join('asdf')

'a-s-d-f'

`-` 예제4

In [274]:
'-'.join(['a','s','d','f'])

'a-s-d-f'

## 2. `list`

### A. 선언

`-` 리스트의 선언

In [277]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

`-` 비어있는 리스트의 선언

In [280]:
a= []
a

[]

In [281]:
a= list()
a

[]

### B. 연산

`-` 더하기연산

In [283]:
[1,2,3] + [-3,4,5]

[1, 2, 3, -3, 4, 5]

-   우리의 예상과 다른 결과가 나옴 $\to$ 파이썬은 R처럼 자체적으로 좋은 계산기능을 내장하고 있지 않음.

`-` 브로드캐스팅과 같이 R에서는 당연히 가능했던 기능을 사용할 수 없음.

In [284]:
[1,2,3,4,5] + 1

TypeError: can only concatenate list (not "int") to list

`-` 뺄셈은 정의되지 않음

In [291]:
a= [1,2,1,2]
a-[1,2]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

`-` 곱하기는 정의가능

In [293]:
[1,2]*3

[1, 2, 1, 2, 1, 2]

`-` 나눗셈은 정의되지 않음

In [294]:
[1,2,1,2,1,2] /3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

`-` 더하기와 곱하기는 원소의 추가와 반복추가를 의미하지만 그렇다고 해서 뺄셈과 나눗셈이 원소의 삭제를 의미하는것은 아님

`-` 더하기와 곱하기가 원소의 추가와 반복추가를 의미하여 편리할때도 있긴하지만, 우리는 산술적인 `+`, `*` 를 원하는 경우도 있다. 이럴 경우는 어떻게 할 수 있을까?

(예제)

In [295]:
a=[1,2]
b=[3,4]

a+b = \[4,6\] 이 되도록 하려면?

(풀이1)

In [307]:
[a[0]+b[0], a[1]+b[1]]

[4, 6]

풀이가 가능한 이유? a,b는 리스트이지만 a\[0\], a\[1\], b\[0\], b\[1\] 은 각각 인트형임. 인트형은 + 연산이 가능했음.

(풀이2)

In [308]:
import numpy 

In [315]:
a=[1,2]
b=[3,4]

In [316]:
aa = numpy.array(a)
bb = numpy.array(b)

In [318]:
a

[1, 2]

In [320]:
aa+bb

array([4, 6])

여러가지 연산 가능 (마치 R처럼 쓸 수 있음)

In [324]:
2*aa

array([2, 4])

In [325]:
2*aa+1

array([3, 5])

In [326]:
2*aa+1+bb

array([6, 9])

(풀이3)

In [334]:
import numpy as np ## 설치가 되어있는 numpy라는 패키지를 쓰겠음. 그런데 numpy말고 np라는 이름으로 쓰겠음

In [335]:
np.array(a)

array([1, 2])

In [336]:
np.array(a)+np.array(b)

array([4, 6])

### C. 인덱싱

`-` str형과 동일한 방식

In [344]:
a=[11,22,33,44,55]

In [345]:
a[-2:] # 끝의 2개의 원소를 뽑음 

[44, 55]

### D. 콘테이너형 객체로서의 리스트

`-` 리스트의 원소는 int, float 따위만 가능한 것이 아니다. (리스트는 컨테이너형 객체이므로)

In [347]:
x = [True, False, True, 2]
x

[True, False, True, 2]

In [348]:
lst = [1,3.14,True,'a',[1,2], 
       (1,2),{'name':'iu','age':27},{1,2,3}]
lst

[1, 3.14, True, 'a', [1, 2], (1, 2), {'name': 'iu', 'age': 27}, {1, 2, 3}]

`-` str은 컨테이너형이 아니다.

In [349]:
'asdf'

'asdf'

-   str의 모든 원소는 문자임

### E. 가변객체

`-` 리스트는 원소를 수정할 수 있다. (리스트는 가변객체이므로)

In [376]:
a = [11,22,33]
a

[11, 22, 33]

In [377]:
a[0] = -77

In [378]:
a

[-77, 22, 33]

`-` 원소수정은 당연한 기능같은데 이것이 불가능한 경우도 있다.

(가능한경우)

In [379]:
a=['g','u','e','b','i','n']
a

['g', 'u', 'e', 'b', 'i', 'n']

In [380]:
a[0] = 'G'

In [381]:
a

['G', 'u', 'e', 'b', 'i', 'n']

(불가능한경우)

In [382]:
a='guebin'
a

'guebin'

In [383]:
a[0]

'g'

In [384]:
a[0]='G'

TypeError: 'str' object does not support item assignment

*만약에 억지로 바꾸고 싶다면?*

In [389]:
l = list(a)
l[0] = 'G'
''.join(l)

'Guebin'

### F. 리스트의 원소 삭제

(예제1) del을 이용한 원소삭제

아래와 같이 문자로 된 리스트를 선언하자.

In [395]:
a = ['g','u','e','b','i','n']
a

['g', 'u', 'e', 'b', 'i', 'n']

***사실 더 쉽게 선언할 수 있음***

In [396]:
list('guebin')

['g', 'u', 'e', 'b', 'i', 'n']

첫번째 원소를 삭제하고 싶다면?

In [398]:
del a[0]

In [399]:
a

['u', 'e', 'b', 'i', 'n']

이 상태에서 다시 첫번째 원소를 삭제한다면?

In [400]:
del a[0]

In [401]:
a

['e', 'b', 'i', 'n']

(예제2) pop을 이용한 원소삭제

In [402]:
a=list('guebin')
a

['g', 'u', 'e', 'b', 'i', 'n']

In [403]:
a.pop(0)

'g'

In [404]:
a

['u', 'e', 'b', 'i', 'n']

In [405]:
a.pop(0)

'u'

In [406]:
a

['e', 'b', 'i', 'n']

(예제3) remove를 이용한 원소삭제

In [407]:
a=list('guebin')
a

['g', 'u', 'e', 'b', 'i', 'n']

In [408]:
a.remove('b')
a

['g', 'u', 'e', 'i', 'n']

### G. 리스트 원소 추가

(예제) 비어있는 리스트를 만들고 원소 0,1,2를 차례로 추가하여 보자.

(풀이1) `+` 연산이용

In [411]:
a=[]
a

[]

In [415]:
a= a+[0]
a

[0]

In [416]:
a= a+[1] # a = [0]+[1]
a

[0, 1]

In [417]:
a= a+[2] # a = [0,1] + [2]
a

[0, 1, 2]

(풀이2) `+=` 이용

In [420]:
a = []
a += [0]
a += [1] 
a += [2] 
a

[0, 1, 2]

-   반복되는 문자를 제거하고 연산의 순서를 바꾼다.

(풀이3) 리스트 특수기능 `.append()`를 이용

In [421]:
a=[] 

In [428]:
a.append(0)
a.append(1)
a.append(2)
a

[0, 1, 2, 0, 1, 2]

### H. `a+[4]`와 `a.append(4)`의 차이점은?

(관찰1)

In [441]:
a=[1,2,3]
a+[4] ## 리스트 a와 리스트 [4]의 연산결과를 알려줘 

[1, 2, 3, 4]

In [442]:
a ## a는 그대로임. 변화없음 

[1, 2, 3]

(관찰2)

In [443]:
a=[1,2,3]
a.append(4)

In [444]:
a ## a자체가 변화함 

[1, 2, 3, 4]

비슷해보이지만 굉장히 미묘한 차이가 있음

`a.append(4)`: `a`에 4를 append하라 $\to$ `a`가 변함

`a+[4]`: `a`와 `[4]`를 연산하라

### I. 리스트 특수기능

**(append)**

In [445]:
a=[1,2,3,4]
a.append?

Signature: a.append(object, /)
Docstring: Append object to the end of the list.
Type:      builtin_function_or_method

In [446]:
a.append(5)
a

[1, 2, 3, 4, 5]

**(clear)**

In [447]:
a=[1,2,3,4]
a.clear?

Signature: a.clear()
Docstring: Remove all items from list.
Type:      builtin_function_or_method

In [448]:
a.clear()
a

[]

**(copy)**

In [449]:
a=[1,2,3,4]
a.copy?

Signature: a.copy()
Docstring: Return a shallow copy of the list.
Type:      builtin_function_or_method

In [450]:
b=a.copy()
b

[1, 2, 3, 4]

**(count)**

In [451]:
a=['a','a','b','b','b','c']
a.count?

Signature: a.count(value, /)
Docstring: Return number of occurrences of value.
Type:      builtin_function_or_method

In [453]:
a.count('a')

2

In [454]:
a.count('b')

3

In [455]:
a.count('c')

1

**(extend)**

In [470]:
a=[1,2,3,4]
b=[-1,-2,-3,-4]

In [471]:
a.extend(b)
a

[1, 2, 3, 4, -1, -2, -3, -4]

In [472]:
a=[1,2,3,4]
b=[-1,-2,-3,-4]

In [473]:
a.append(b)

In [474]:
a

[1, 2, 3, 4, [-1, -2, -3, -4]]

**(index)**

In [477]:
a=[11,22,'a',True, 22,'a']
a.index?

Signature: a.index(value, start=0, stop=9223372036854775807, /)
Docstring:
Return first index of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method

In [114]:
a.index(11)

0

In [115]:
a.index(22)

1

In [116]:
a.index('a')

2

In [117]:
a.index(True)

3

**(insert)**

In [482]:
a=[11,22,33]
a.insert?

Signature: a.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method

In [484]:
a.insert(2,88) 
a

[11, 22, 88, 88, 33]

**(pop)**

In [485]:
a=['a',1,2,'d']
a.pop?

Signature: a.pop(index=-1, /)
Docstring:
Remove and return item at index (default last).

Raises IndexError if list is empty or index is out of range.
Type:      builtin_function_or_method

In [486]:
a.pop() # index=-1 이므로 마지막원소가 나타남

'd'

In [487]:
a # a는 마지막 원소가 사라진 상태

['a', 1, 2]

In [488]:
a.pop(0) # index=0 이므로 첫번쨰 원소가 나타남

'a'

In [489]:
a # a에는 첫번째 원소가 사라진 상태

[1, 2]

**(remove)**

In [490]:
a=['a',2,3,'d']
a.remove?

Signature: a.remove(value, /)
Docstring:
Remove first occurrence of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method

In [491]:
a.remove('d')

In [492]:
a

['a', 2, 3]

In [493]:
a.remove('a')

In [494]:
a

[2, 3]

**(reverse)**

In [495]:
a=[1,2,3,4]
a.reverse?

Signature: a.reverse()
Docstring: Reverse *IN PLACE*.
Type:      builtin_function_or_method

In [496]:
a.reverse()
a

[4, 3, 2, 1]

**(sort)**

In [497]:
a=[1,3,2,4]
a.sort?

Signature: a.sort(*, key=None, reverse=False)
Docstring:
Sort the list in ascending order and return None.

The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
order of two equal elements is maintained).

If a key function is given, apply it once to each list item and sort them,
ascending or descending, according to their function values.

The reverse flag can be set to sort in descending order.
Type:      builtin_function_or_method

In [498]:
a.sort()
a

[1, 2, 3, 4]

In [501]:
a.sort(reverse=True)
a

[4, 3, 2, 1]

(다른예제들)

In [506]:
a=list('guebin')
a

['g', 'u', 'e', 'b', 'i', 'n']

In [507]:
a.sort()
a

['b', 'e', 'g', 'i', 'n', 'u']

In [508]:
a.sort(reverse=True)
a

['u', 'n', 'i', 'g', 'e', 'b']

### J. 중첩리스트

`-` 리스트는 리스트를 원소로 받을 수 있으므로 아래와 같이 중첩된
리스트를 만들 수 있다.

In [524]:
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

`-` A는 1차원인 벡터가 아니라 2차원인 매트릭스로 이해할 수 있다.
구체적으로는 아래와 같은 매트릭스로 이해할 수 있다

$$\bf{A}=\begin{bmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9 
\end{bmatrix}$$

`-` A에서 (2,1)의 원소를 뽑고싶다 = 4를 뽑고싶다

In [532]:
A[1,0] # R에서는 이게 가능했죠

TypeError: list indices must be integers or slices, not tuple

-   실패

In [533]:
A[1][0]

4

-   성공

`-` 성공의 이유를 분석해보자.

In [534]:
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [535]:
A[1]

[4, 5, 6]

In [536]:
A[1][0]

4

`-` 매트릭스는 아니지만 매트릭스 같음!

-   1차원 배열을 다차원 배열로 확장할 수 있는 기본 아이디어를 제공함

### K. 리스트 컴프리헨션

`-` 개념: 집합에서 $\{10,20,30,40\}=\{10i: i=1,2,3,4\}=\big\{10i: \text{ for } i \in \{1,2,3,4\}\big\}$ 임을 떠올리자. 

In [545]:
[10,20,30,40]

[10, 20, 30, 40]

In [546]:
[10*i for i in [1,2,3,4]]

[10, 20, 30, 40]

`-` 예제1: 리스트 컴프리헨션을 이용하여 아래와 같은 리스트를 만들어라.

In [143]:
['SSSS','PPPP','AAAA','MMMM']

['SSSS', 'PPPP', 'AAAA', 'MMMM']

(풀이)

In [553]:
[s*4 for s in 'SPAM']

['SSSS', 'PPPP', 'AAAA', 'MMMM']

`-` 예제2: 리스트컴프리헨션을 이용하여 아래와 같은 리스트를 만들어라.

In [145]:
['X1','X2','X3','Y1','Y2','Y3']

['X1', 'X2', 'X3', 'Y1', 'Y2', 'Y3']

(풀이)

In [564]:
[i+j for i in 'XY' for j in '123']

['X1', 'X2', 'X3', 'Y1', 'Y2', 'Y3']

`-` 예제: 리스트컴프리헨션을 이용하여 아래와 같은 리스트를 만들어라.

In [573]:
['stat1', 'stat2', 'stat3', 'math1', 'math2', 'math3']

['stat1', 'stat2', 'stat3', 'math1', 'math2', 'math3']

(풀이)

In [574]:
[i+j for i in ['stat','math'] for j in '123']

['stat1', 'stat2', 'stat3', 'math1', 'math2', 'math3']

(다른풀이) 비어있는 리스트를 만들고 for문을 쓰면 좀 복잡해진다.

In [575]:
lst = [] 
for x in ['stat','math']: 
    for y in '123': 
        lst.append(x+y)
lst

['stat1', 'stat2', 'stat3', 'math1', 'math2', 'math3']

`-` 예제: 리스트컴프리헨션과 문자열 `'jbnu'`를 이용하여 아래와 같은
리스트를 만들어라.

In [576]:
['j','b','n','u']

['j', 'b', 'n', 'u']

(풀이)

In [585]:
[s for s in 'jbnu']

['j', 'b', 'n', 'u']

(다른풀이) 아래와 같이 풀면 된다는것은 알고 있음

In [586]:
list('jbnu')

['j', 'b', 'n', 'u']

`-` 예제: 리스트컴프리헨션을 이용하여 아래와 같은 리스트를 만들어라.

In [157]:
['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12']

['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12']

(풀이)

In [600]:
['X'+str(i) for i in range(1,13)]

['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12']

### L. 리스트 컴프리헨션과 for문의 미묘한 차이

(경우1)

In [603]:
x=777 
lst = [] 
for x in 'jbnu': 
    lst = lst + [x]
lst    

['j', 'b', 'n', 'u']

In [604]:
x

'u'

(경우2)

In [607]:
x=777
lst = [x for x in 'jbnu'] 
lst 

['j', 'b', 'n', 'u']

In [608]:
x

777

> 진짜 미묘하게 다르죠?

### M. 연습문제들

`# 문제`. 길이가 0인 리스트를 만들어라. (비어있는 리스트를 만들어라)

(풀이)

In [614]:
a = []

In [615]:
len(a)

0

`# 문제`. 다음의 실행값 중 가장 큰 숫자가 나오는 보기를 골라라. (에러가 나는 코드는 정답에서 제외함)

``` python
(a) len(3.14) 
(b) len([3.14]) 
(c) len('3.14') 
```

(풀이)

In [619]:
len('3.14') # c가 제일큼

4

`# 문제`. 리스트자료형의 `+`와 `*` 연산을 이용하여 아래와 같은 list를
생성하라.

In [192]:
[1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5]

[1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5]

**hint:** 아래의 코드를 관찰해보세요

In [620]:
[1]*1+[2]*2 

[1, 2, 2]

(풀이)

In [630]:
lst =[]
for i in range(1,6):
    lst.extend([i]*i)
lst

[1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5]

`# 문제`. 다음과 같은 리스트를 고려하자.

In [632]:
lst = ['A','B','C','D','A','A','B','A','F','C','C','C','A']

이 리스트에서 ‘A’ 혹은 ’B’의 숫자는 모두 몇개인가?

(풀이)

In [633]:
lst.count("A")

5

In [634]:
lst.count("B")

2

`# 문제`. 아래와 같은 문자열이 있다고 하자.

In [637]:
test_arr = 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAklOUpkDHrfHY17SbrmTIpNLTGK9Tjom/BWDSUGPl+nafzlHDTYW7hdI4yZ5ew18JH4JW9jbhUFrviQzM7xlELEVf4h9lFX5QVkbPppSwg0cda3Pbv7kOdJ/MTyBlWXFCR+HAo3FXRitBqxiX1nKhXpHAZsMciLq8V6RjsNAQwdsdMFvSlVK/7XAt3FaoJoAsncM1Q9x5+3V0Ww68/eIFmb1zuUFljQJKprrX88XypNDvjYNby6vw/Pb0rwert/EnmZ+AW4OZPnTPI89ZPmVMLuayrD2cE86Z/il8b+gw3r3+1nKatmIkjn2so1d01QraTlMqVSsbxNrRFi9wrf+M7Q== schacon@mylaptop.local'

이 문자열에서 대문자의 수를 count하라.

**hint: `str` 자료형의 특수기능 `.isupper()` 를 이용할 것**

(풀이)

In [645]:
sum([s.isupper() for s in test_arr])

155

`# 문제`. 리스트컴프리헨션을 이용하여 아래와 같은 리스트를 생성하라.

    ['a',
     'aa',
     'aaa',
     'aaaa',
     'aaaaa',
     'aaaaaa',
     'aaaaaaa',
     'aaaaaaaa',
     'aaaaaaaaa',
     'aaaaaaaaaa'] <- a가 10개있음

(풀이)

In [650]:
lst = ['a'*i for i in range(1,11)]
lst

['a',
 'aa',
 'aaa',
 'aaaa',
 'aaaaa',
 'aaaaaa',
 'aaaaaaa',
 'aaaaaaaa',
 'aaaaaaaaa',
 'aaaaaaaaaa']

`# 문제`. 아래와 같은 리스트를 관찰하라.

In [653]:
lst = ['2022/09/21','2022/10/30','2022/12/25','2023/01/01','2023/01/31','2023/03/20']
lst

['2022/09/21',
 '2022/10/30',
 '2022/12/25',
 '2023/01/01',
 '2023/01/31',
 '2023/03/20']

이러한 리스트를 아래와 같은 리스트로 변환하는 코드를 작성하라.

In [654]:
['2022-09-21', '2022-10-30', '2022-12-25', '2023-01-01', '2023-01-31', '2023-03-20']

['2022-09-21',
 '2022-10-30',
 '2022-12-25',
 '2023-01-01',
 '2023-01-31',
 '2023-03-20']

**hint: string의 `.replace()`기능과 리스트 컴프리헨션의 응용**

(풀이)

In [659]:
[l.replace('/','-') for l in lst]

['2022-09-21',
 '2022-10-30',
 '2022-12-25',
 '2023-01-01',
 '2023-01-31',
 '2023-03-20']

`# 문제`. 아래와 같이 하나의 특수문자로 이루어진 리스트를 고려하자.

In [660]:
block = ['■'] 

이를 이용하여 아래와 같은 결과를 출력하라.

In [187]:
'■-■-■-■-■-■-■-■-■-■' # 여기에서 '■'는 모두 10개 있음

'■-■-■-■-■-■-■-■-■-■'

(풀이1)

In [671]:
'-'.join(block*10)

'■-■-■-■-■-■-■-■-■-■'

(풀이2)

In [667]:
((block[0]+'-')*10)[:-1]

'■-■-■-■-■-■-■-■-■-■'

## 3. HW

`1`. 아래를 출력하는 코드를 작성하라. 

```bash
11x1=11
11x2=22
11x3=33
...
19x17=323
19x18=342
19x19=361
```

`(풀이)`

In [688]:
# for j in range(11,20):
#     for i in range(1,20):
#         print(f"{j}x{i}={j*i}")

`2`. 아래와 같은 리스트를 관찰하라. 

In [689]:
lst = ['2022/09/21','2022/10/30','2022/12/25','2023/01/01','2023/01/31','2023/03/20']
lst

['2022/09/21',
 '2022/10/30',
 '2022/12/25',
 '2023/01/01',
 '2023/01/31',
 '2023/03/20']

이러한 리스트를 아래와 같은 리스트로 변환하는 코드를 작성하라.

In [690]:
['22-09-21.','22-10-30.','22-12-25.','23-01-01.','23-01-31.','23-03-20.']

['22-09-21.', '22-10-30.', '22-12-25.', '23-01-01.', '23-01-31.', '23-03-20.']

`(풀이)`

In [697]:
[l[2:].replace("/","-")+"." for l in lst]

['22-09-21.', '22-10-30.', '22-12-25.', '23-01-01.', '23-01-31.', '23-03-20.']